[package]
name = "rust-https-redirect"
version = "0.1.0"
authors = ["Manatsawin Hanmongkolchai <manatsawin+git@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp.git" }
